TRUNCATE TABLE admin.datatransfer_tables;

INSERT INTO admin.datatransfer_tables(source_database_name, source_table_name, source_where_clause, target_schema_name, target_table_name, target_excluded_columns)
VALUES
 ('sau_web', 'Area', NULL, 'web', 'area', '{}'::TEXT[]) 
,('sau_web', 'AreaInvisible', NULL, 'web', 'area_invisible', '{}'::TEXT[])
,('sau_web', 'CommercialGroups', NULL, 'web', 'commercial_groups', '{}'::TEXT[])
,('sau_web', 'Country_EEZcountry', NULL, 'web', 'country', '{}'::TEXT[])
,('sau_web', 'Country_EEZngo', NULL, 'web', 'country_ngo', ARRAY['country_ngo_id']::TEXT[])
,('sau_web', 'Country_FishProfile', NULL, 'web', 'country_fishery_profile', '{}'::TEXT[])
,('sau_web', 'Cube_AreaData', 'WHERE [versionid] = 2', 'web', 'cube_area_data', ARRAY['catch_type_id', 'sector_type_id']::TEXT[])
,('sau_web', 'Cube_DimTaxon', NULL, 'web', 'cube_dim_taxon', '{}'::TEXT[])
,('sau_web', 'EEZ', NULL, 'web', 'eez', '{}'::TEXT[])
,('sau_web', 'FaoArea', NULL, 'web', 'fao_area', '{}'::TEXT[])
,('sau_web', 'FishingEntity', NULL, 'web', 'fishing_entity', '{}'::TEXT[])
,('sau_web', 'FunctionalGroups', NULL, 'web', 'functional_groups', '{}'::TEXT[])
,('sau_web', 'Gear', NULL, 'web', 'gear', '{}'::TEXT[])
,('sau_web', 'GeoEntity', 'ORDER BY abs([GeoEntityID] - [AdminGeoEntityID])', 'web', 'geo_entity', '{}'::TEXT[])
,('sau_web', 'GeoEntity_MaricultureEntity_Mapping', NULL, 'web', 'geo_entity_mariculture_entity_mapping', '{}'::TEXT[])
,('sau_web', 'Internal_New_Taxon', NULL, 'web', 'internal_new_taxon', '{}'::TEXT[])
,('sau_web', 'Jurisdiction', NULL, 'web', 'jurisdiction', '{}'::TEXT[])
,('sau_web', 'LME', NULL, 'web', 'lme', '{}'::TEXT[])
,('sau_web', 'MaricultureData', NULL, 'web', 'mariculture_data', '{}'::TEXT[])
,('sau_web', 'MaricultureEntity', NULL, 'web', 'mariculture_entity', '{}'::TEXT[])
,('sau_web', 'MaricultureSubEntity', NULL, 'web', 'mariculture_sub_entity', ARRAY['lat', 'long', 'geom', 'point_geom']::TEXT[])
,('sau_web', 'MarineLayer', NULL, 'web', 'marine_layer', '{}'::TEXT[])
,('sau_web', 'ReconstructionPaper', NULL, 'web', 'reconstruction_paper', '{}'::TEXT[])
,('sau_web', 'RFMO', NULL, 'web', 'rfmo', '{}'::TEXT[])
,('sau_web', 'SubGeoEntity', NULL, 'web', 'sub_geo_entity', '{}'::TEXT[])
,('sau_web', 'Time', NULL, 'web', 'time', '{}'::TEXT[])
,('sau_web', 'Legacy_EEZestuary', NULL, 'web', 'estuary', '{}'::TEXT[])
,('sau_web', 'Subsidy_Definition', NULL, 'web', 'subsidy_definition', '{}'::TEXT[])
,('sau_web', 'Subsidy_RefDefinition', NULL, 'web', 'subsidy_ref_definition', '{}'::TEXT[])
,('sau_web', 'Subsidy_RefMapping', NULL, 'web', 'subsidy_ref_mapping', '{}'::TEXT[])
,('sau_web', 'Subsidy', NULL, 'web', 'subsidy', ARRAY['year']::TEXT[])
,('sau_web', 'Legacy_HabitatIndex', NULL, 'web', 'habitat_index', '{}'::TEXT[])
,('sau_web', 'Tropics_MainArea', NULL, 'web_report', 'tropics_main_area', '{}'::TEXT[])
,('sau_web', 'Tropics_SubArea', NULL, 'web_report', 'tropics_sub_area', '{}'::TEXT[])
,('sau_web', 'PersianGulf_SubArea', NULL, 'web_report', 'persian_gulf_sub_area', '{}'::TEXT[])
,('sau_web', 'BalticData', NULL, 'web_report', 'baltic_data', '{}'::TEXT[])
,('sau_web', 'BayOfBengal', NULL, 'web_report', 'bay_of_bengal', '{}'::TEXT[])
,('sau_allocation_20150325', 'CatchType', NULL, 'allocation', 'catch_type', '{}'::TEXT[])
,('sau_allocation_20150325', 'SectorType', NULL, 'allocation', 'sector_type', '{}'::TEXT[])
--,('sau_allocation_20150325', 'Cell', NULL, 'allocation', 'cell', '{}'::TEXT[])
--,('sau_allocation_20150325', 'CellToEEZ', NULL, 'allocation', 'cell_to_eez', '{}'::TEXT[])
--,('sau_allocation_20150325', 'AllocationSimpleArea', NULL, 'allocation', 'allocation_simple_area', '{}'::TEXT[])
--,('sau_allocation_20150325', 'SimpleAreaCellAssignment', NULL, 'allocation', 'simple_area_cell_assignment', '{}'::TEXT[])
,('sau_allocation_20150325', 'AllocationAreaType', NULL, 'allocation', 'allocation_area_type', '{}'::TEXT[])
,('sau_allocation_20150325', 'Layer', NULL, 'allocation', 'layer', '{}'::TEXT[])
;

-- Below are tables to be processed with multiple threads each due to their size
INSERT INTO admin.datatransfer_tables(source_database_name, source_table_name, source_where_clause, target_schema_name, target_table_name, target_excluded_columns, source_key_column, number_of_threads)
VALUES
 ('MerlinAgg', 'Data', NULL, 'allocation', 'allocation_data', '{}'::TEXT[], 'UniversalDataID', 9)
,('MerlinAgg', 'AllocationResult_EEZ', NULL, 'allocation', 'allocation_result_eez', '{}'::TEXT[], 'UniversalDataID', 9)
,('MerlinAgg', 'AllocationResult_Global', NULL, 'allocation', 'allocation_result_global', '{}'::TEXT[], 'UniversalDataID', 9)
,('MerlinAgg', 'AllocationResult_LME', NULL, 'allocation', 'allocation_result_lme', '{}'::TEXT[], 'UniversalDataID', 9)
,('Merlin', 'Price', NULL, 'allocation', 'price', '{}'::TEXT[], NULL::VARCHAR, 2)
,('Merlin', 'TaxonDistribution', NULL, 'allocation', 'taxon_distribution', '{}'::TEXT[], 'TaxonDistributionID', 9)
;
