/* Reconstruction data tables */
CREATE TABLE recon.catch(
  id serial primary key,
  fishing_entity_id int null,
  original_country_fishing varchar(255) null,
  eez_id int null,
  sub_area_eez varchar(255) null,
  fao_area_id int null,
  sub_regional_area varchar(255) null,
  province_state varchar(255) null,
  ices_division varchar(255) null,
  ices_sub_division varchar(255) null,
  nafo_division varchar(255) null,
  ccamlr_area varchar(255) null,
  year int null,
  taxon_key int null,
  original_fao_name varchar(255) null,
  catch_amount float null,
  adjustment_factor varchar(255) null,
  gear_code int null,
  gear_type varchar(255) null,
  sector varchar(255) null,
  original_sector varchar(255) null,
  catch_type varchar(255) null,
  catch_type_id int null,
  input varchar(255) null,
  forward_carry_rule varchar(255) null,
  reference_id int null,
  notes text null,
  data_row_id int null
);                         

CREATE TABLE recon.template(
  fishing_entity text,
  original_country_fishing text,
  eez text,
  eez_sub_area text,
  fao_area int,
  sub_regional_area text,
  province text,
  ices_divison text,
  ices_subdivision text,
  nafo_division text,
  ccamlr_area text,
  layer int,
  sector text,
  original_sector text,
  catch_type text,
  year int,
  taxon_name text,
  original_taxon_name text,
  original_fao_name text,
  amount numeric,
  adjustment_factor numeric,
  gear_type gear,
  input_type text,
  forward_carry_rule text,
  disaggregation_rule text,
  layer_rule text,
  reference_id int,
  notes text
);
